language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  # Install Mongo PHP Driver (BSON)
  - pecl -q install mongo && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  # Composer Setup
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

after_script:
  - php vendor/bin/coveralls
